INSERT INTO cotacao_diaria (ACAO, DATA, VALOR) VALUES ('PETR4', PARSEDATETIME ('01-02-17','dd-MM-yy'), 100.3);
INSERT INTO cotacao_diaria (ACAO, DATA, VALOR) VALUES ('PETR4', PARSEDATETIME ('02-02-17','dd-MM-yy'), 99.1);
INSERT INTO cotacao_diaria (ACAO, DATA, VALOR) VALUES ('PETR4', PARSEDATETIME ('03-02-17','dd-MM-yy'), 101.5);
INSERT INTO cotacao_diaria (ACAO, DATA, VALOR) VALUES ('PETR4', PARSEDATETIME ('04-02-17','dd-MM-yy'), 98.3);
INSERT INTO cotacao_diaria (ACAO, DATA, VALOR) VALUES ('PETR4', PARSEDATETIME ('05-02-17','dd-MM-yy'), 97.5);
INSERT INTO cotacao_diaria (ACAO, DATA, VALOR) VALUES ('PETR4', PARSEDATETIME ('06-02-17','dd-MM-yy'), 98.6);
INSERT INTO cotacao_diaria (ACAO, DATA, VALOR) VALUES ('PETR4', PARSEDATETIME ('07-02-17','dd-MM-yy'), 100.7);
